from __future__ import annotations

from typing import Any


class AppControllerContract:
    """IDE contract for cross-mixin attributes (PyCharm static analysis)."""

    CAN_FILTER_FIELDS: tuple[str, ...]

    # Qt signals used across mixins.
    autoDetectEnabledChanged: Any
    autoResetBeforeProgrammingChanged: Any
    calibrationBackupChanged: Any
    calibrationNodeSelectionChanged: Any
    calibrationPollingIntervalChanged: Any
    calibrationStateChanged: Any
    calibrationTempCompChanged: Any
    calibrationValuesChanged: Any
    calibrationVerificationChanged: Any
    calibrationWizardChanged: Any
    collectorCyclePauseChanged: Any
    collectorEnabledChanged: Any
    collectorNodesChanged: Any
    collectorOutputDirectoryChanged: Any
    collectorPollIntervalChanged: Any
    collectorDiagnosticsChanged: Any
    collectorStateChanged: Any
    collectorTrendEnabledChanged: Any
    collectorTrendChanged: Any
    collectorSftpChanged: Any
    canFilterOptionsChanged: Any
    canJournalEnabledChanged: Any
    canTrafficLogsChanged: Any
    connectionStateChanged: Any
    debugEnabledChanged: Any
    deviceInfoChanged: Any
    devicesChanged: Any
    firmwareLoadingChanged: Any
    firmwarePathChanged: Any
    infoMessage: Any
    logsChanged: Any
    observedUdsCandidateChanged: Any
    optionHistoryChanged: Any
    optionsBulkChanged: Any
    optionsBulkRowsChanged: Any
    optionOperationChanged: Any
    optionSelectionChanged: Any
    optionValueChanged: Any
    optionsTargetNodeChanged: Any
    programmingActiveChanged: Any
    progressChanged: Any
    selectedDeviceIndexChanged: Any
    serviceAccessChanged: Any
    sourceAddressBusyChanged: Any
    sourceAddressOperationChanged: Any
    sourceAddressTextChanged: Any
    traceStateChanged: Any
    transferByteOrderIndexChanged: Any
    udsIdentifiersChanged: Any

    # Runtime state attributes initialized in AppController.__init__.
    _auto_detect_enabled: Any
    _auto_reset_before_programming: Any
    _auto_reset_delay_ms: Any
    _bootloader: Any
    _calibration_active: Any
    _calibration_backup_available: Any
    _calibration_backup_level_0: Any
    _calibration_backup_level_100: Any
    _calibration_backup_pending: Any
    _calibration_backup_values_pending: Any
    _calibration_captured_available: Any
    _calibration_captured_level: Any
    _calibration_current_level: Any
    _calibration_level0_written: Any
    _calibration_level100_written: Any
    _calibration_level_0: Any
    _calibration_level_0_known: Any
    _calibration_level_100: Any
    _calibration_level_100_known: Any
    _calibration_node_options: Any
    _calibration_node_values: Any
    _calibration_temp_comp_dataset_options: Any
    _calibration_temp_comp_dataset_values: Any
    _selected_calibration_temp_comp_dataset_index: Any
    _calibration_poll_interval_ms: Any
    _calibration_poll_timer: Any
    _calibration_read_service: Any
    _calibration_recent_samples: Any
    _calibration_recent_window_sec: Any
    _calibration_restore_active: Any
    _calibration_restore_current_did: Any
    _calibration_restore_queue: Any
    _calibration_session_ready: Any
    _calibration_session_service: Any
    _calibration_target_node_sa: Any
    _calibration_runtime_target_sa: Any
    _calibration_temp_comp_status: Any
    _calibration_temp_comp_operation_text: Any
    _calibration_temp_comp_operation_busy: Any
    _calibration_temp_comp_operation_progress_percent: Any
    _calibration_temp_comp_operation_progress_determinate: Any
    _calibration_temp_comp_preview_status: Any
    _calibration_temp_comp_preview_busy: Any
    _calibration_temp_comp_preview_progress_percent: Any
    _calibration_temp_comp_preview_progress_determinate: Any
    _calibration_temp_comp_samples: Any
    _calibration_temp_comp_samples_by_node: Any
    _calibration_temp_comp_sample_limit: Any
    _calibration_temp_comp_last_period: Any
    _calibration_temp_comp_last_temperature_x10: Any
    _calibration_temp_comp_last_temperature_c: Any
    _calibration_temp_comp_k1_x100_current: Any
    _calibration_temp_comp_k1_x100_base: Any
    _calibration_temp_comp_k1_x100_recommended: Any
    _calibration_temp_comp_k1_x100_delta: Any
    _calibration_temp_comp_k1_x100_next: Any
    _calibration_temp_comp_linear_preview_enabled: Any
    _calibration_temp_comp_linear_preview_k1_x100: Any
    _calibration_temp_comp_linear_preview_k0_count: Any
    _calibration_temp_comp_advanced_values: Any
    _calibration_temp_comp_adv_read_active: Any
    _calibration_temp_comp_adv_read_queue: Any
    _calibration_temp_comp_adv_read_inflight_key: Any
    _calibration_temp_comp_adv_read_total_count: Any
    _calibration_temp_comp_adv_read_success_count: Any
    _calibration_temp_comp_adv_read_mode_aware: Any
    _calibration_temp_comp_adv_read_expected_mode: Any
    _calibration_temp_comp_adv_read_recompute_pending: Any
    _calibration_temp_comp_adv_read_timeout_ms: Any
    _calibration_temp_comp_adv_read_delay_ms: Any
    _calibration_temp_comp_adv_read_timeout_timer: Any
    _calibration_temp_comp_adv_read_delay_timer: Any
    _calibration_temp_comp_recommendation_apply_queue: Any
    _calibration_temp_comp_k0_air_zero_adjust_active: Any
    _calibration_temp_comp_k0_air_zero_adjust_empty_period: Any
    _calibration_temp_comp_k0_air_zero_adjust_full_period: Any
    _calibration_temp_comp_k0_air_zero_adjust_level_x10: Any
    _calibration_temp_comp_k0_air_zero_adjust_current_k0: Any
    _calibration_temp_comp_k0_air_zero_adjust_timeout_ms: Any
    _calibration_temp_comp_k0_air_zero_adjust_timeout_timer: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_active: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_empty_period: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_full_period: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_level_x10: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_level_samples: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_required_samples: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_stability_threshold_x10: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_current_zero_trim: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_timeout_ms: Any
    _calibration_temp_comp_zero_trim_air_zero_adjust_timeout_timer: Any
    _calibration_temp_comp_zero_trim_count_current: Any
    _calibration_temp_comp_zero_trim_count_recommended: Any
    _calibration_temp_comp_zero_trim_count_delta: Any
    _calibration_temp_comp_zero_trim_count_next: Any
    _calibration_temp_comp_zero_trim_residual_x10: Any
    _calibration_temp_comp_zero_trim_last_report: Any
    _calibration_temp_comp_zero_trim_verify_pending: Any
    _calibration_temp_comp_zero_trim_verify_timeout_ms: Any
    _calibration_temp_comp_zero_trim_verify_tolerance_x10: Any
    _calibration_temp_comp_zero_trim_verify_repeat_threshold_x10: Any
    _calibration_temp_comp_zero_trim_verify_timeout_timer: Any
    _calibration_temp_comp_period_slope_before: Any
    _calibration_temp_comp_period_slope_after: Any
    _calibration_temp_comp_level_slope_before: Any
    _calibration_temp_comp_level_slope_after: Any
    _calibration_temp_comp_period_reduction_percent: Any
    _calibration_temp_comp_level_reduction_percent: Any
    _calibration_temp_comp_chart_series: Any
    _calibration_temp_comp_chart_revision: Any
    _calibration_verify0_ok: Any
    _calibration_verify100_ok: Any
    _calibration_verify_tolerance: Any
    _calibration_waiting_session: Any
    _calibration_wizard_hint: Any
    _calibration_wizard_stage: Any
    _calibration_write_service: Any
    _calibration_write_verify_pending: Any
    _can: Any
    _can_filter_option_limits: Any
    _can_filter_option_seen: Any
    _can_filter_options: Any
    _can_filter_rebuild_timer: Any
    _can_filter_values: Any
    _can_journal_enabled: Any
    _can_traffic_logs: Any
    _collector_combined_csv_manager: Any
    _collector_diagnostics_rate_limit: Any
    _collector_error_log_limit: Any
    _collector_error_logs: Any
    _collector_pending_requests: Any
    _collector_pending_timeout_ms: Any
    _collector_max_pending_requests: Any
    _collector_min_inter_request_ms: Any
    _collector_last_request_monotonic: Any
    _collector_csv_managers: Any
    _collector_cycle_pause_ms: Any
    _collector_enabled: Any
    _collector_node_order: Any
    _collector_nodes: Any
    _collector_nodes_view: Any
    _collector_output_directory: Any
    _collector_output_is_session_dir: Any
    _collector_poll_interval_ms: Any
    _collector_poll_node_index: Any
    _collector_poll_phase: Any
    _collector_poll_timer: Any
    _collector_poll_vars: Any
    _collector_read_service: Any
    _collector_session_dir: Any
    _collector_state: Any
    _collector_trend_enabled: Any
    _collector_trend_caption: Any
    _collector_trend_csv_series: Any
    _collector_trend_history_limit: Any
    _collector_trend_latest_fuel: Any
    _collector_trend_latest_temperature: Any
    _collector_trend_max_points: Any
    _collector_trend_metrics_rows: Any
    _collector_trend_network_metrics: Any
    _collector_trend_nodes_view: Any
    _collector_trend_points: Any
    _collector_trend_points_by_node: Any
    _collector_sftp_enabled: Any
    _collector_sftp_host: Any
    _collector_sftp_port: Any
    _collector_sftp_username: Any
    _collector_sftp_password: Any
    _collector_sftp_remote_dir: Any
    _collector_sftp_busy: Any
    _collector_sftp_status_text: Any
    _collector_sftp_uploader: Any
    _collector_view_update_pending_nodes: Any
    _collector_view_update_pending_trend: Any
    _collector_view_update_timer: Any
    _debug_enabled: Any
    _device_handle: Any
    _device_indices: Any
    _devices: Any
    _filtered_can_traffic_logs: Any
    _firmware: Any
    _firmware_loader_thread: Any
    _firmware_loader_worker: Any
    _firmware_loading: Any
    _firmware_path: Any
    _logs: Any
    _manufacturer: Any
    _observed_candidate_index: Any
    _observed_candidate_items: Any
    _observed_candidate_order: Any
    _observed_candidate_values: Any
    _observed_frame_seq: Any
    _observed_node_stats: Any
    _observed_uds_text: Any
    _options_busy: Any
    _options_bulk_busy: Any
    _options_bulk_delay_ms: Any
    _options_bulk_fail_count: Any
    _options_bulk_next_index: Any
    _options_bulk_plan: Any
    _options_bulk_rows: Any
    _options_bulk_status: Any
    _options_bulk_step_timer: Any
    _options_bulk_success_count: Any
    _options_history: Any
    _options_history_next_id: Any
    _options_isotp_buffer: Any
    _options_isotp_next_sn: Any
    _options_isotp_total_len: Any
    _options_items: Any
    _options_last_read_bytes: Any
    _options_fc_retry_left: Any
    _options_fc_retry_timer: Any
    _options_parameters: Any
    _options_pending_action: Any
    _options_pending_did: Any
    _options_pending_target_sa: Any
    _options_pending_write_bytes: Any
    _options_request_origin: Any
    _options_raw_hex: Any
    _options_read_service: Any
    _options_selected_access: Any
    _options_selected_can_read: Any
    _options_selected_can_write: Any
    _options_selected_did: Any
    _options_selected_name: Any
    _options_selected_note: Any
    _options_selected_size: Any
    _options_status: Any
    _options_target_node_items: Any
    _options_target_node_sa: Any
    _options_target_node_values: Any
    _options_timeout_timer: Any
    _options_value_text: Any
    _options_write_service: Any
    _pending_programming_after_reset: Any
    _perf_origin: Any
    _project_root_directory: Any
    _product: Any
    _programming_active: Any
    _programming_start_timer: Any
    _progress_max: Any
    _progress_value: Any
    _rx_dst_text: Any
    _rx_identifier_text: Any
    _rx_pgn_text: Any
    _rx_priority_text: Any
    _rx_src_text: Any
    _rx_time_anchor_raw: Any
    _rx_time_anchor_wall: Any
    _selected_calibration_node_index: Any
    _selected_device_index: Any
    _selected_service_session_index: Any
    _selected_option_index: Any
    _selected_options_target_node_index: Any
    _serial: Any
    _service_access_busy: Any
    _service_access_pending_action: Any
    _service_access_status: Any
    _service_access_target_sa: Any
    _service_access_timeout_timer: Any
    _service_security_access_service: Any
    _service_security_unlocked: Any
    _service_session_items: Any
    _service_session_service: Any
    _source_address_busy: Any
    _source_address_operation: Any
    _source_address_text: Any
    _transfer_byte_order_index: Any
    _tx_dst_text: Any
    _tx_identifier_text: Any
    _tx_pgn_text: Any
    _tx_priority_text: Any
    _tx_src_text: Any
    _ui_ecu_reset_service: Any
    _wall_origin: Any

    # Fallback for cross-mixin methods/fields to avoid unresolved warnings in IDE.
    def __getattr__(self, name: str) -> Any: ...
