from __future__ import annotations

from typing import Any


class AppControllerContract:
    """IDE contract for cross-mixin attributes (PyCharm static analysis)."""

    CAN_FILTER_FIELDS: tuple[str, ...]

    # Qt signals used across mixins.
    autoDetectEnabledChanged: Any
    autoResetBeforeProgrammingChanged: Any
    calibrationBackupChanged: Any
    calibrationNodeSelectionChanged: Any
    calibrationPollingIntervalChanged: Any
    calibrationStateChanged: Any
    calibrationZeroTrimChanged: Any
    calibrationValuesChanged: Any
    calibrationVerificationChanged: Any
    calibrationWizardChanged: Any
    collectorCyclePauseChanged: Any
    collectorEnabledChanged: Any
    collectorNodesChanged: Any
    collectorOutputDirectoryChanged: Any
    collectorPollIntervalChanged: Any
    collectorDiagnosticsChanged: Any
    collectorStateChanged: Any
    collectorTrendEnabledChanged: Any
    collectorTrendChanged: Any
    collectorSftpChanged: Any
    canFilterOptionsChanged: Any
    canJournalEnabledChanged: Any
    canTrafficLogsChanged: Any
    connectionStateChanged: Any
    debugEnabledChanged: Any
    deviceInfoChanged: Any
    devicesChanged: Any
    diagnosticsChanged: Any
    profileChanged: Any
    mediaWizardChanged: Any
    firmwareLoadingChanged: Any
    firmwarePathChanged: Any
    infoMessage: Any
    logsChanged: Any
    observedUdsCandidateChanged: Any
    optionHistoryChanged: Any
    programmingBatchChanged: Any
    programmingNodeSelectionChanged: Any
    protocolControlChanged: Any
    optionsBulkChanged: Any
    optionsBulkRowsChanged: Any
    optionOperationChanged: Any
    optionSelectionChanged: Any
    optionValueChanged: Any
    optionsTargetNodeChanged: Any
    programmingActiveChanged: Any
    progressChanged: Any
    selectedDeviceIndexChanged: Any
    serviceAccessChanged: Any
    softwareVersionChanged: Any
    sourceAddressBusyChanged: Any
    sourceAddressOperationChanged: Any
    sourceAddressStatusChanged: Any
    sourceAddressTextChanged: Any
    traceStateChanged: Any
    transferByteOrderIndexChanged: Any
    udsIdentifiersChanged: Any

    # Runtime state attributes initialized in AppController.__init__.
    _media_wizard_action: Any
    _media_wizard_air: Any
    _media_wizard_busy: Any
    _media_wizard_cal: Any
    _media_wizard_enabled: Any
    _media_wizard_gap_timer: Any
    _media_wizard_live_raw: Any
    _media_wizard_live_spread: Any
    _media_wizard_pending: Any
    _media_wizard_read_service: Any
    _media_wizard_samples: Any
    _media_wizard_status: Any
    _media_wizard_status_color: Any
    _media_wizard_timeout_timer: Any
    _media_wizard_watching: Any
    _media_wizard_write_service: Any
    _profile_algorithm_id: Any
    _profile_busy: Any
    _profile_verify: Any
    _profile_verify_report: Any
    _profile_device_crc: Any
    _profile_device_crc_actual: Any
    _profile_device_status: Any
    _profile_file_path: Any
    _profile_generation: Any
    _profile_queue: Any
    _profile_status: Any
    _profile_status_color: Any
    _profile_values: Any
    _chamber_read_service: Any
    _chamber_label: Any
    _chamber_points: Any
    _chamber_busy: Any
    _chamber_status: Any
    _chamber_status_color: Any
    _chamber_report: Any
    _chamber_file_path: Any
    _chamber_rehearsal: Any
    _chamber_extend_liquid: Any
    _chamber_span_main: Any
    _chamber_span_media: Any
    _chamber_queue: Any
    _chamber_pending: Any
    _chamber_sample: Any
    _chamber_samples: Any
    _chamber_samples_left: Any
    _chamber_gap_timer: Any
    _chamber_timeout_timer: Any
    chamberChanged: Any
    trialChanged: Any
    _trial_read: Any
    _trial_write: Any
    _trial_steps_state: Any
    _trial_busy: Any
    _trial_status: Any
    _trial_status_color: Any
    _trial_log: Any
    _trial_ops: Any
    _trial_pending: Any
    _trial_results: Any
    _trial_done_handler: Any
    _trial_backup: Any
    _trial_expected: Any
    _trial_rf_deadline: Any
    _trial_level_reading: Any
    _trial_media_points: Any
    _trial_chamber_outcome: Any
    _trial_applied_profile: Any
    _trial_chamber_plan: Any
    _trial_chamber_index: Any
    _trial_gap_timer: Any
    _trial_wait_timer: Any
    _trial_timeout_timer: Any
    _trial_poll_timer: Any
    _diagnostics_counter_delta: Any
    _diagnostics_counter_growing: Any
    _diagnostics_counter_prev: Any
    _diagnostics_cycles_done: Any
    _diagnostics_j1939_raw: Any
    _diagnostics_j1939_seen_s: Any
    _diagnostics_gap_timer: Any
    _diagnostics_missing: Any
    _diagnostics_pending: Any
    _diagnostics_queue: Any
    _diagnostics_read_service: Any
    _diagnostics_rows: Any
    _diagnostics_running: Any
    _diagnostics_status: Any
    _diagnostics_summary_color: Any
    _diagnostics_summary_text: Any
    _diagnostics_timeout_timer: Any
    _diagnostics_values: Any
    _auto_detect_enabled: Any
    _auto_reset_before_programming: Any
    _auto_reset_delay_ms: Any
    _bootloader: Any
    _calibration_active: Any
    _calibration_backup_available: Any
    _calibration_backup_file_path: Any
    _calibration_backup_loaded_from_file: Any
    _calibration_backup_node_sa: Any
    _calibration_backup_saved_at_text: Any
    _calibration_backup_source_text: Any
    _calibration_backup_k0: Any
    _calibration_backup_k1: Any
    _calibration_backup_level_0: Any
    _calibration_backup_level_100: Any
    _calibration_backup_zero_trim: Any
    _calibration_dump_capture_active: Any
    _calibration_dump_capture_current_did: Any
    _calibration_dump_capture_queue: Any
    _calibration_dump_capture_target_sa: Any
    _calibration_dump_capture_timeout_ms: Any
    _calibration_dump_capture_timeout_timer: Any
    _calibration_dump_capture_values: Any
    _calibration_backup_pending: Any
    _calibration_backup_values_pending: Any
    _calibration_captured_available: Any
    _calibration_captured_level: Any
    _calibration_current_level: Any
    _calibration_level0_written: Any
    _calibration_level100_written: Any
    _calibration_level_0: Any
    _calibration_level_0_known: Any
    _calibration_level_100: Any
    _calibration_level_100_known: Any
    _calibration_node_options: Any
    _calibration_node_values: Any
    _calibration_poll_interval_ms: Any
    _calibration_poll_timer: Any
    _calibration_read_service: Any
    _calibration_recent_samples: Any
    _calibration_recent_window_sec: Any
    _calibration_restore_active: Any
    _calibration_restore_current_did: Any
    _calibration_restore_queue: Any
    _calibration_session_ready: Any
    _calibration_session_service: Any
    _calibration_target_node_sa: Any
    _calibration_runtime_target_sa: Any
    _calibration_zero_trim_operation_text: Any
    _calibration_zero_trim_operation_busy: Any
    _calibration_zero_trim_operation_progress_percent: Any
    _calibration_zero_trim_operation_progress_determinate: Any
    _calibration_zero_trim_air_zero_adjust_active: Any
    _calibration_zero_trim_air_zero_adjust_empty_period: Any
    _calibration_zero_trim_air_zero_adjust_full_period: Any
    _calibration_zero_trim_air_zero_adjust_level_x10: Any
    _calibration_zero_trim_air_zero_adjust_level_samples: Any
    _calibration_zero_trim_air_zero_adjust_required_samples: Any
    _calibration_zero_trim_air_zero_adjust_stability_threshold_x10: Any
    _calibration_zero_trim_air_zero_adjust_current_zero_trim: Any
    _calibration_zero_trim_air_zero_adjust_timeout_ms: Any
    _calibration_zero_trim_air_zero_adjust_timeout_timer: Any
    _calibration_zero_trim_count_current: Any
    _calibration_zero_trim_count_recommended: Any
    _calibration_zero_trim_count_delta: Any
    _calibration_zero_trim_count_next: Any
    _calibration_zero_trim_residual_x10: Any
    _calibration_zero_trim_last_report: Any
    _calibration_zero_trim_csv_log_path: Any
    _calibration_zero_trim_verify_pending: Any
    _calibration_zero_trim_verify_timeout_ms: Any
    _calibration_zero_trim_verify_tolerance_x10: Any
    _calibration_zero_trim_verify_repeat_threshold_x10: Any
    _calibration_zero_trim_verify_retries_left: Any
    _calibration_zero_trim_verify_retries_max: Any
    _calibration_zero_trim_verify_timeout_timer: Any
    _calibration_verify0_ok: Any
    _calibration_verify100_ok: Any
    _calibration_verify_tolerance: Any
    _calibration_waiting_session: Any
    _calibration_wizard_hint: Any
    _calibration_wizard_stage: Any
    _calibration_write_service: Any
    _calibration_write_verify_pending: Any
    _can: Any
    _can_filter_option_limits: Any
    _can_filter_option_seen: Any
    _can_filter_options: Any
    _can_filter_rebuild_timer: Any
    _can_filter_values: Any
    _can_journal_enabled: Any
    _can_traffic_logs: Any
    _collector_combined_csv_manager: Any
    _collector_diagnostics_rate_limit: Any
    _collector_error_log_limit: Any
    _collector_error_logs: Any
    _collector_pending_requests: Any
    _collector_pending_timeout_ms: Any
    _collector_max_pending_requests: Any
    _collector_min_inter_request_ms: Any
    _collector_last_request_monotonic: Any
    _collector_csv_managers: Any
    _collector_cycle_pause_ms: Any
    _collector_enabled: Any
    _collector_node_order: Any
    _collector_nodes: Any
    _collector_nodes_view: Any
    _collector_output_directory: Any
    _collector_output_is_session_dir: Any
    _collector_poll_interval_ms: Any
    _collector_poll_node_index: Any
    _collector_poll_phase: Any
    _collector_poll_timer: Any
    _collector_poll_vars: Any
    _collector_read_service: Any
    _collector_session_dir: Any
    _collector_state: Any
    _collector_trend_enabled: Any
    _collector_trend_caption: Any
    _collector_trend_csv_series: Any
    _collector_trend_history_limit: Any
    _collector_trend_latest_fuel: Any
    _collector_trend_latest_temperature: Any
    _collector_trend_max_points: Any
    _collector_trend_metrics_rows: Any
    _collector_trend_network_metrics: Any
    _collector_trend_nodes_view: Any
    _collector_trend_points: Any
    _collector_trend_points_by_node: Any
    _collector_sftp_enabled: Any
    _collector_sftp_host: Any
    _collector_sftp_port: Any
    _collector_sftp_username: Any
    _collector_sftp_password: Any
    _collector_sftp_remote_dir: Any
    _collector_sftp_busy: Any
    _collector_sftp_status_text: Any
    _collector_sftp_uploader: Any
    _collector_view_update_pending_nodes: Any
    _collector_view_update_pending_trend: Any
    _collector_view_update_timer: Any
    _debug_enabled: Any
    _device_handle: Any
    _device_indices: Any
    _devices: Any
    _filtered_can_traffic_logs: Any
    _firmware: Any
    _firmware_loader_thread: Any
    _firmware_loader_worker: Any
    _firmware_loading: Any
    _firmware_path: Any
    _logs: Any
    _manufacturer: Any
    _observed_candidate_index: Any
    _observed_candidate_items: Any
    _observed_candidate_order: Any
    _observed_candidate_values: Any
    _observed_frame_seq: Any
    _observed_node_stats: Any
    _observed_uds_text: Any
    _options_busy: Any
    _options_bulk_busy: Any
    _options_bulk_delay_ms: Any
    _options_bulk_fail_count: Any
    _options_bulk_next_index: Any
    _options_bulk_plan: Any
    _options_bulk_rows: Any
    _options_bulk_status: Any
    _options_bulk_step_timer: Any
    _options_bulk_success_count: Any
    _options_history: Any
    _options_history_next_id: Any
    _options_isotp_buffer: Any
    _options_isotp_next_sn: Any
    _options_isotp_total_len: Any
    _options_write_isotp_active: Any
    _options_write_isotp_waiting_fc: Any
    _options_write_isotp_cf_frames: Any
    _options_items: Any
    _options_last_read_bytes: Any
    _options_fc_retry_left: Any
    _options_fc_retry_timer: Any
    _options_parameters: Any
    _options_pending_action: Any
    _options_pending_did: Any
    _options_pending_target_sa: Any
    _options_pending_write_bytes: Any
    _options_request_origin: Any
    _options_raw_hex: Any
    _options_read_service: Any
    _options_selected_access: Any
    _options_selected_can_read: Any
    _options_selected_can_write: Any
    _options_selected_did: Any
    _options_selected_name: Any
    _options_selected_note: Any
    _options_selected_size: Any
    _options_status: Any
    _options_target_node_items: Any
    _options_target_node_sa: Any
    _options_target_node_values: Any
    _options_timeout_timer: Any
    _options_value_text: Any
    _options_write_service: Any
    _software_version_did: Any
    _software_version_text: Any
    _software_version_status: Any
    _software_version_busy: Any
    _firmware_file_version_text: Any
    _supplier_did_rows: Any
    _supplier_did_status_text: Any
    _supplier_did_bulk_busy: Any
    _supplier_did_bulk_queue: Any
    _supplier_did_bulk_total: Any
    _supplier_did_bulk_done: Any
    _supplier_did_bulk_success: Any
    _supplier_did_bulk_fail: Any
    _communication_control_mode_items: Any
    _selected_communication_control_mode_index: Any
    _communication_control_addressing_items: Any
    _selected_communication_control_addressing_index: Any
    _communication_control_type_items: Any
    _selected_communication_control_type_index: Any
    _communication_control_suppress_positive_response: Any
    _communication_control_busy: Any
    _communication_control_status: Any
    _communication_control_pending_target_sa: Any
    _communication_control_pending_sub_function: Any
    _communication_control_pending_suppress: Any
    _communication_control_pending_functional: Any
    _communication_control_expected_response_sas: Any
    _communication_control_functional_response_sas: Any
    _communication_control_service: Any
    _communication_control_timeout_timer: Any
    _pending_programming_after_reset: Any
    _perf_origin: Any
    _project_root_directory: Any
    _product: Any
    _programming_active: Any
    _programming_batch_active: Any
    _programming_batch_delay_ms: Any
    _programming_batch_done: Any
    _programming_batch_queue: Any
    _programming_batch_status: Any
    _programming_batch_step_timer: Any
    _programming_batch_total: Any
    _programming_current_target_sa: Any
    _programming_node_items: Any
    _programming_node_values: Any
    _programming_start_timer: Any
    _programming_target_status: Any
    _post_program_version_write_pending: Any
    _post_program_version_write_stage: Any
    _post_program_version_write_target_sa: Any
    _post_program_version_write_primary_sa: Any
    _post_program_version_write_fallback_used: Any
    _post_program_version_write_value: Any
    _post_program_version_write_delay_ms: Any
    _post_program_version_write_max_retry_count: Any
    _post_program_version_write_retry_left: Any
    _post_program_version_write_wait_logged: Any
    _post_program_version_write_timer: Any
    _progress_max: Any
    _progress_value: Any
    _rx_dst_text: Any
    _rx_identifier_text: Any
    _rx_pgn_text: Any
    _rx_priority_text: Any
    _rx_src_text: Any
    _rx_time_anchor_raw: Any
    _rx_time_anchor_wall: Any
    _selected_calibration_node_index: Any
    _selected_device_index: Any
    _selected_programming_node_index: Any
    _selected_service_session_index: Any
    _selected_option_index: Any
    _selected_options_target_node_index: Any
    _serial: Any
    _service_access_busy: Any
    _service_access_pending_action: Any
    _service_access_status: Any
    _service_access_target_sa: Any
    _service_access_timeout_timer: Any
    _service_security_access_service: Any
    _service_security_unlocked: Any
    _service_session_items: Any
    _service_session_service: Any
    _source_address_busy: Any
    _source_address_operation: Any
    _source_address_status: Any
    _source_address_pending_target_sa: Any
    _source_address_pending_new_sa: Any
    _source_address_read_service: Any
    _source_address_write_service: Any
    _source_address_timeout_timer: Any
    _source_address_text: Any
    _transfer_byte_order_index: Any
    _tx_dst_text: Any
    _tx_identifier_text: Any
    _tx_pgn_text: Any
    _tx_priority_text: Any
    _tx_src_text: Any
    _ui_ecu_reset_service: Any
    _wall_origin: Any

    # Fallback for cross-mixin methods/fields to avoid unresolved warnings in IDE.
    def __getattr__(self, name: str) -> Any: ...
